// Central list of application error codes
export enum ErrorCode {
  // Validation
  VALIDATION_EMAIL_INVALID = 'VALIDATION_EMAIL_INVALID',
  VALIDATION_PASSWORD_INVALID = 'VALIDATION_PASSWORD_INVALID',
  VALIDATION_REQUIRED = 'VALIDATION_REQUIRED',
  VALIDATION_CPF_CNPJ_INVALID = 'VALIDATION_CPF_CNPJ_INVALID',
  VALIDATION_SIZE_EXCEEDED = 'VALIDATION_SIZE_EXCEEDED',
  VALIDATION_INCONSISTENT = 'VALIDATION_INCONSISTENT',

  // Auth / Session
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  AUTH_ACCOUNT_UNVERIFIED = 'AUTH_ACCOUNT_UNVERIFIED',
  AUTH_ACCOUNT_BLOCKED = 'AUTH_ACCOUNT_BLOCKED',
  AUTH_ACCOUNT_SUSPENDED = 'AUTH_ACCOUNT_SUSPENDED',
  AUTH_TOO_MANY_ATTEMPTS = 'AUTH_TOO_MANY_ATTEMPTS',
  AUTH_SESSION_EXPIRED = 'AUTH_SESSION_EXPIRED',
  AUTH_TOKEN_INVALID = 'AUTH_TOKEN_INVALID',
  AUTH_TOKEN_EXPIRED = 'AUTH_TOKEN_EXPIRED',
  AUTH_2FA_INVALID = 'AUTH_2FA_INVALID',
  AUTH_2FA_REQUIRED = 'AUTH_2FA_REQUIRED',
  AUTH_DEVICE_UNTRUSTED = 'AUTH_DEVICE_UNTRUSTED',
  AUTH_EMAIL_NOT_FOUND = 'AUTH_EMAIL_NOT_FOUND',
  AUTH_ACCOUNT_LOCKED = 'AUTH_ACCOUNT_LOCKED',
  AUTH_PASSWORD_EXPIRED = 'AUTH_PASSWORD_EXPIRED',
  AUTH_LOGIN_REQUIRED = 'AUTH_LOGIN_REQUIRED',
  AUTH_API_UNAVAILABLE = 'AUTH_API_UNAVAILABLE',

  // Authorization
  PERMISSION_DENIED = 'PERMISSION_DENIED',

  // Resource
  NOT_FOUND = 'NOT_FOUND',
  CONFLICT = 'CONFLICT',

  // Password recovery / onboarding
  RECOVERY_EMAIL_NOT_FOUND = 'RECOVERY_EMAIL_NOT_FOUND',
  RECOVERY_LINK_INVALID = 'RECOVERY_LINK_INVALID',
  RECOVERY_SAME_PASSWORD = 'RECOVERY_SAME_PASSWORD',
  SIGNUP_EMAIL_EXISTS = 'SIGNUP_EMAIL_EXISTS',
  SIGNUP_WEAK_PASSWORD = 'SIGNUP_WEAK_PASSWORD',
  SIGNUP_TERMS_NOT_ACCEPTED = 'SIGNUP_TERMS_NOT_ACCEPTED',
  SIGNUP_COMPANY_EXISTS = 'SIGNUP_COMPANY_EXISTS',

  // Network / Server / DB
  NETWORK_OFFLINE = 'NETWORK_OFFLINE',
  NETWORK_TIMEOUT = 'NETWORK_TIMEOUT',
  SERVER_UNAVAILABLE = 'SERVER_UNAVAILABLE',
  SERVER_ERROR = 'SERVER_ERROR',
  DB_UNAVAILABLE = 'DB_UNAVAILABLE',
  RATE_LIMITED = 'RATE_LIMITED',
  UNPROCESSABLE = 'UNPROCESSABLE',

  // Files
  FILE_UNSUPPORTED = 'FILE_UNSUPPORTED',
  FILE_TOO_LARGE = 'FILE_TOO_LARGE',
  FILE_UPLOAD_FAILED = 'FILE_UPLOAD_FAILED',
  FILE_UPLOAD_CANCELED = 'FILE_UPLOAD_CANCELED',

  // Integrations
  INTEGRATION_UNAVAILABLE = 'INTEGRATION_UNAVAILABLE',
  INTEGRATION_API_KEY_INVALID = 'INTEGRATION_API_KEY_INVALID',
  INTEGRATION_QUOTA_EXCEEDED = 'INTEGRATION_QUOTA_EXCEEDED',

  // Application
  PREFS_SAVE_FAILED = 'PREFS_SAVE_FAILED',
  VERSION_OUTDATED = 'VERSION_OUTDATED',
  UNKNOWN = 'UNKNOWN',
}

export const AllErrorCodes: ReadonlySet<string> = new Set(Object.values(ErrorCode))

