export const MOCK_DETALHE = {
  id: 19,
  numero: "ORC-00019",
  cliente: "Metal Forte",
  projeto: "Guindaste Colunar - Cap. 2t",
  responsavel: "Ana",
  emissao: "2025-08-17",
  validade: "2025-09-01",
  status: "em análise",
  margem: 0.25,
  condPgto: "30/60/90 (Boleto)",
  entrega: "FOB - 30 dias após aprovação",
  garantia: "12 meses contra defeitos de fabricação",
  observacoes: "Preços válidos para pagamento dentro do prazo e sem retenções.",
  slaDias: 2,
  enviado: true,
  respondeuEm: null,
  rev: 0,
  itens: [
    { id: crypto.randomUUID(), categoria: "Máquinas & Equipamentos", codigo: "EQ-2001", nome: "Coluna metálica 6m - ASTM A36", un: "un", qtd: 1, preco: 68000 },
    { id: crypto.randomUUID(), categoria: "Materiais / Matéria-prima", codigo: "MP-3110", nome: "Chapas 1/2\" oxicorte", un: "kg", qtd: 500, preco: 18.9 },
    { id: crypto.randomUUID(), categoria: "Consumíveis", codigo: "CS-0901", nome: "Eletrodos E7018", un: "cx", qtd: 3, preco: 780 },
    { id: crypto.randomUUID(), categoria: "Serviços", codigo: "SV-1200", nome: "Pintura epóxi PU", un: "m²", qtd: 120, preco: 35 },
    { id: crypto.randomUUID(), categoria: "Mão de Obra", codigo: "MO-0100", nome: "Soldador nível II", un: "h", qtd: 80, preco: 65 },
    { id: crypto.randomUUID(), categoria: "Ferramentas & Acessórios", codigo: "FR-5520", nome: "Talha elétrica 2t (importada)", un: "un", qtd: 1, preco: 14500 },
  ],
  fin: { descontoPct: 3, descontoValor: 0, frete: 2500, outrosCustos: 1800, issPct: 3, icmsPct: 12, pisPct: 1.65, cofinsPct: 7.6 },
  anexos: [
    { id: crypto.randomUUID(), nome: "Desenho Guindaste - Vista Geral.pdf", tipo: "pdf" },
    { id: crypto.randomUUID(), nome: "Memorial de Cálculo - V1.xlsx", tipo: "xlsx" },
  ],
  historico: [
    { data: "2025-08-17T09:15:00", tipo: "criado", desc: "Orçamento criado por Ana" },
    { data: "2025-08-17T09:40:00", tipo: "enviado", desc: "Proposta enviada por e-mail ao cliente" },
    { data: "2025-08-19T16:05:00", tipo: "interacao", desc: "Cliente solicitou detalhamento de pintura" },
  ],
} as const;
